### ISSUE TITLE
Got a Problem with latest Source

### ISSUE THREAD

**Issue by Nackenschelle** [Account-Managers/Account-Manager#11]
Fody: Error writing IntermediateCopyLocalFilesCache: Could not find a part of the path 'C:\Account-Manager\DraconiusGoGUI\obj\Release\'.

did i miss somethin in the latest updates?

**Comment by Nackenschelle** [comment]
ok i fixed the issue by my own but now i cannot open design windows -.-

Error: The base class 'System.Windows.Forms.Form' could not be loaded.  Ensure the assembly has been referenced and that all projects have been built.

did a reinstall of visual studio maybe fix this issue?

**Comment by Furtif** [comment]
@Nackenschelle build is fine if not fine appveyor bugs !!! https://ci.appveyor.com/project/RocketBot/account-manager/branch/master look you visual basic read the readme file into git for dependencies

**Comment by Furtif** [comment]
but for now no works need update for new app

**Comment by Nackenschelle** [comment]
ok thanks for the quick awnser

issue can be closed

**Comment by Furtif** [comment]
@Nackenschelle updated for compatibility at last app

**Comment by Furtif** [comment]
join discord at link into readme for other issues thank for rapport.
