### ISSUE TITLE
Some features not working

### ISSUE THREAD

**Issue by Nackenschelle** [Account-Managers/Account-Manager#2]
hey i found out that the bot wont catch any creature he only runs from stop to stop without spinning them.
any solution for me?

**Comment by m3g4mInD** [comment]
@Nackenschelle  have you read all? For the moment our draco bot can login and spin "buildings" , is not finnish for the moment, in next weeks all gonna be fine, keep touch on our discord server  [https://discord.gg/WpUmKX](url)
